### ISSUE TITLE
Remove reliance on `{sp}` and `{raster}`

### ISSUE THREAD

**Issue by benjaminhlina** [AgrDataSci/gdistance#22]
Hi Andrew, 

Are there plans to transition `{gdistance}` from relying on `{sp}` and `{raster}` to `{sf}` and `{terra}`. I currently use some of the functions in the package to determine the shortest paths between locations inside a confined boundary. I have transitioned to using another package, `{pathroutr}`, to do this considering the archival of `{sp}` and `{raster}` but would like to use functions from your package. 

Thanks,
Ben

**Comment by andrewmarx** [comment]
Hi Ben, my understanding is that the `{raster}` and `{sp}` packages will continue to be maintained at a minimal level because of the number of packages and old work that depends on them. Their dependencies on `{rgdal}` and `{rgeos}` were replaced to facilitate this (the raster package now uses `{terra}` internally). If I'm wrong, please link relevant material so I can plan accordingly.

With that said, transitioning to `{terra}` was a goal when I took over maintenance of gdistance, but I've since realized that it may not be possible without breaking a lot of old code and packages dependent on `{gdistance}`. The problem is that `{gdistance}` doesn't just use functions from `{raster}`, but that `TransitionLayer-class` directly inherits from `BasicRaster-class` in the `{raster}` package. This means that `TransitionLayer-class` objects inherently contain things like `Extent-class` (`{raster}`) and `CRS-class` (`{sp}`). So anyone with old code reliant on those classes could see their work break in the transition to `{terra}` and `{sp}` equivalents.

So, for now, I'm a little wary about going in and messing with these things unless I can be sure the transition will be straightforward. Should the `{raster}` or `{sp}` packages look like they will be removed from CRAN, then I will reevaluate. I still might not make the switch and just let `{gdistance}` die peacefully. But I won't let that happen without a reasonable alternative package for people to turn to. Right now, I'm trying to figure out the best way to replicate most of the `{gdistance}` functionality into `{samc}`

**Comment by benjaminhlina** [comment]
Hi @andrewmarx thank for the further info regarding `{gdistance}` and the packages it depends on. I was not fully aware that `{raster}` and `{sp}` were going to be maintained at a minimum level which is good to know. I appreciate your explanation regarding `TransitionLayer-class` and why changing anything at this point doesn't make sense and maybe never will with `{gdistance}` dying peacefully. Good to know that `{smac}` is potentially an alternative to `{gdistance}`. 

Thanks again for your response and providing more context.
