### ISSUE TITLE
Error: vector memory exhausted (limit reached?) on geoCorrection call?

### ISSUE THREAD

**Issue by lplough** [AgrDataSci/gdistance#24]
Running geoCorrection() on an object raster_tr 

```raster_tr
class      : TransitionLayer 
dimensions : 7775, 5101, 39660275  (nrow, ncol, ncell)
resolution : 0.01000125, 0.01000092  (x, y)
extent     : -98.1, -47.0836, -35.38177, 42.37537  (xmin, xmax, ymin, ymax)
crs        : +proj=longlat +datum=WGS84 +no_defs 
values      : conductance 
matrix class: dsCMatrix
```

I get the vector memory exhausted (limit reached) error. Im trying to correct the map before make shortest path estimates. 

Here is the specific call: 

``` raster_tr_corrected <- geoCorrection(raster_tr, type="c", multpl=FALSE)```

I am running on MacOSX with 16gb RAM, using gdistance version 1.6.4. Is there a way to increase my memory to avoid this error or any other tips? 

Thanks!

LP

**Comment by andrewmarx** [comment]
Sorry, but this isn't really a bug. In order to do the geocorrection, it's allocating an extremely large vector. One that is large enough that your computer's RAM can't hold it all. Your only real option is probably to find a different computer with more RAM. I don't know exactly how much, though.

Alternatively, you can try scaling down your raster. It might give a reasonable estimate, depending on the data and how you scale it. It's hard to say for sure, but maybe try multiple scales and see if the results tend to asymptote as the scale gets larger. But you have to be careful if there are small influential details that could be lost with scaling. Otherwise, I'm not really in a position to provide more guidance on the matter.
